name: Tests

on:
  push:
    branches: [ master, windows-support ]

env:
  TZ: "Europe/Berlin"

jobs:
  unittest:
    name: Unittests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest]
        java-version: [ 17, 21, 25 ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Set timezone on Windows
        if: matrix.os == 'windows-latest'
        run: |
          tzutil /g
          tzutil /s "W. Europe Standard Time"
          tzutil /g
      - name: Compile
        run: mvn compile
#      - name: Verify
#        run: mvn --batch-mode test -D"org.slf4j.simpleLogger.defaultLogLevel"="error" -D"org.slf4j.simpleLogger.log.de.neuland.pug4j"="debug" -D"test"="PugLexerTest"
      - name: Verify all
        run: mvn --batch-mode --update-snapshots verify

